// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-gXuOlH3magZNMuJzRHljbefR74k4VI',
    appId: '1:641902590935:web:d85222894ad5b87416e992',
    messagingSenderId: '641902590935',
    projectId: 'brewhelpy',
    authDomain: 'brewhelpy.firebaseapp.com',
    storageBucket: 'brewhelpy.appspot.com',
    measurementId: 'G-SM9QQ3CJ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XKIhlHhVS5ZAc3TIBRE0ULmbnEjz3zc',
    appId: '1:641902590935:android:4db759cae6912f0216e992',
    messagingSenderId: '641902590935',
    projectId: 'brewhelpy',
    storageBucket: 'brewhelpy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiEziVgSDQvbeQ0IHNlL_AjHhNJlwrjb8',
    appId: '1:641902590935:ios:59d30107061fd26c16e992',
    messagingSenderId: '641902590935',
    projectId: 'brewhelpy',
    storageBucket: 'brewhelpy.appspot.com',
    iosBundleId: 'com.example.brewhelpy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiEziVgSDQvbeQ0IHNlL_AjHhNJlwrjb8',
    appId: '1:641902590935:ios:59d30107061fd26c16e992',
    messagingSenderId: '641902590935',
    projectId: 'brewhelpy',
    storageBucket: 'brewhelpy.appspot.com',
    iosBundleId: 'com.example.brewhelpy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-gXuOlH3magZNMuJzRHljbefR74k4VI',
    appId: '1:641902590935:web:dac8ae310fbd3bf616e992',
    messagingSenderId: '641902590935',
    projectId: 'brewhelpy',
    authDomain: 'brewhelpy.firebaseapp.com',
    storageBucket: 'brewhelpy.appspot.com',
    measurementId: 'G-FRHG3BK95V',
  );
}
